version: '2'
services:
  app:
    build: .
    networks:
      - private-network
    expose:
      - "3000"
    ports:
      - "3001:3000"
    volumes:
      - ./public/assets:/app/public/assets

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    networks:
      - private-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/public
    depends_on:
      - app

networks:
  private-network:
    driver: bridge
